{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    {{- include "elastic-gpu-telemetry.serviceLabels" (dict "component" "postgres" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "elastic-gpu-telemetry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}

